/* Standalone mock adapter. Replace these two methods when the API contract is agreed. */
const profileStore = (() => {
  let saved = null;
  return { async loadProfile() { return structuredClone(saved); }, async saveProfile(value) { saved = structuredClone(value); return structuredClone(saved); } };
})();
const blankProfile = () => ({id:crypto.randomUUID(),profileNotes:'',photo:null,displayName:'',ageRange:null,conditions:null,medications:null,dietaryPreferences:null,allergies:null,trackingPreferences:[],devices:null,accessibility:{textSize:'normal',reduceMotion:false},reminders:{checkin:false,medication:false},onboardingCompleted:false});
let setupCompleted=false;
let draft = blankProfile(), step = 0, savedMode = false, editingMedication = null;
const titles = ['About you','Health background','Your medications','Food & preferences','What matters to you','Your devices','App settings','Review your profile'];
const AGE_GROUPS=['','Under 18','18–24','25–44','45–64','65–74','75–84','85+','Prefer not to say'];
const REVIEW_STEP=7;
const form=document.getElementById('setup'), content=document.getElementById('content');
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=(values,selected)=>values.map(v=>`<option value="${escapeHtml(v)}" ${v===selected?'selected':''}>${escapeHtml(v)}</option>`).join('');
const field=(id,label,value='',type='text')=>`<label for="${id}">${label}</label><input id="${id}" type="${type}" value="${escapeHtml(value)}">`;
const checks=(key,values,selected=[])=>`<fieldset><legend>${key==='conditions'?'Select any that apply':'Choose what you want to record'}</legend><div class="choices">${values.map(v=>`<label class="choice"><input type="checkbox" name="${key}" value="${escapeHtml(v)}" ${(selected||[]).includes(v)?'checked':''}>${v}</label>`).join('')}</div></fieldset>`;
const list=value=>value===null?'Not provided':value.length?value.join(', '):'None';
function render(){
 document.body.classList.toggle('setup-complete', setupCompleted);

 document.getElementById('steps').innerHTML=titles.map((t,i)=>`<li class="${i===step?'current':''}" ${i===step?'aria-current="step"':''}>${t}</li>`).join('');
 document.getElementById('progress').textContent=savedMode?'Your profile':`Step ${step+1} of ${titles.length}`;
 document.getElementById('message').textContent='';
 let body='';
 if(savedMode||step===REVIEW_STEP){
 const groups=[['About you',`${draft.displayName||'Name not provided'} · ${draft.ageRange||'Age range not provided'}. ${draft.profileNotes||''}`],['Health background',list(draft.conditions)],['Medications',draft.medications===null?'Not provided':draft.medications.length?draft.medications.map(m=>`${m.name} ${m.dose} · ${m.schedule}`).join('; '):'None'],['Food & preferences',`Diet: ${list(draft.dietaryPreferences)}. Allergies: ${list(draft.allergies)}`],['Recording preferences',`${draft.trackingPreferences.join(', ')||'Not selected'}`],['Your devices',draft.devices===null?'Not provided':draft.devices.length?`${draft.devices.join(', ')} — selected, not connected`:'No devices'],['App settings',`Text size: ${draft.accessibility.textSize}. Reduce motion: ${draft.accessibility.reduceMotion?'Yes':'No'}. Check-in reminders: ${draft.reminders.checkin?'On':'Off'}. Medication reminders: ${draft.reminders.medication?'On':'Off'}`]];
 body=`${savedMode?`<div class="profile-avatar">${draft.photo?`<img src="${draft.photo}" alt="Your profile photo">`:escapeHtml((draft.displayName||'?').charAt(0).toUpperCase())}</div><label for="profilePhoto">Personalize profile photo (optional)</label><input id="profilePhoto" type="file" accept="image/png,image/jpeg,image/webp"><p class="demo">Photo stays in this demo session. PNG, JPEG or WebP, up to 2 MB.</p>`:''}<h2>${savedMode?'Your profile is ready':'Does this look right?'}</h2><p>${savedMode?'Your personal profile is saved for this demo session. After app integration, you can update it in More → Profile. You can personalize it here now.':'Only the information you provided appears below.'}</p>`+groups.map(([title,value],i)=>`<section class="summary"><h3>${title}</h3><p>${escapeHtml(value)}</p><button type="button" data-edit="${i}">Edit ${title.toLowerCase()}</button></section>`).join('');
 }else if(step===0){body=`<h2>What should we call you?</h2><p>Let’s get to know you. These details are for your personal health profile.</p>${field('displayName','Your preferred name',draft.displayName)}<label for="ageRange">Your age group (optional)</label><select id="ageRange">${options(AGE_GROUPS,draft.ageRange||'')}</select><p class="demo">Age groups help organize your profile; they are not used to diagnose or recommend treatment.</p>${field('profileNotes','Anything else you would like us to know? (optional)',draft.profileNotes)}`;
 }else if(step===1){const known=['Chronic disease','Autoimmune condition','POTS','High blood pressure','Heart disease','Type 1 diabetes','Type 2 diabetes','Asthma','COPD / chronic lung disease','Chronic kidney disease','Arthritis','Osteoporosis','Thyroid condition','Chronic pain','Other long-term condition'];body=`<h2>Health background & chronic conditions</h2><p>Include ongoing conditions you have been told you have. Share only what you are comfortable sharing. These are your own reports.</p>${checks('conditions',known,draft.conditions)}${field('conditionOther','Other conditions (separate with commas)',(draft.conditions||[]).filter(c=>!known.includes(c)).join(', '))}<label class="choice"><input type="checkbox" id="noConditions" ${Array.isArray(draft.conditions)&&!draft.conditions.length?'checked':''}>No known health conditions</label>`;
 }else if(step===2){body=`<h2>Current medications</h2><p>Add the details you know. You can leave dose or schedule blank.</p><div id="medList">${(draft.medications||[]).map((m,i)=>`<article class="med"><strong>${escapeHtml(m.name)}</strong><p>${escapeHtml(m.dose)} · ${escapeHtml(m.schedule||'Schedule not provided')}</p><button type="button" data-med-edit="${i}">Edit</button> <button type="button" data-med-delete="${i}">Delete</button></article>`).join('')||'<p>No medications added.</p>'}</div><button type="button" id="addMedication">+ Add medication</button><label class="choice"><input type="checkbox" id="noMedications" ${Array.isArray(draft.medications)&&!draft.medications.length?'checked':''}>I do not take any medications</label><div id="medEditor" hidden class="med-fields"></div>`;
 }else if(step===3){body=`<h2>Food & everyday preferences</h2><p>Diet preferences and allergies are separate. Leave either blank to skip it.</p>${field('diet','Diet preferences (separate with commas)',(draft.dietaryPreferences||[]).join(', '))}<label class="choice"><input type="checkbox" id="noDiet" ${Array.isArray(draft.dietaryPreferences)&&!draft.dietaryPreferences.length?'checked':''}>No dietary preferences</label>${field('allergies','Food allergies (separate with commas)',(draft.allergies||[]).join(', '))}<label class="choice"><input type="checkbox" id="noAllergies" ${Array.isArray(draft.allergies)&&!draft.allergies.length?'checked':''}>No known food allergies</label>`;
 }else if(step===4){body=`<h2>What would you like to track?</h2><p>You can change these choices later. Choosing a measurement does not add a reading.</p>${checks('trackingPreferences',['Symptoms','Medication','Meals','Water','Caffeine','Blood pressure','Blood glucose'],draft.trackingPreferences)}<p class="demo">You can change tracking choices later in More → Profile.</p>`;
 }else if(step===5){const devices=['Apple Watch','WHOOP','Fitbit','Garmin','Oura Ring','Blood pressure monitor','Blood glucose meter / CGM'];body=`<h2>Add your devices</h2><p>Which devices do you use? Select any that apply.</p><fieldset><legend>Devices</legend><div class="choices">${devices.map(device=>`<label class="choice"><input type="checkbox" name="devices" value="${escapeHtml(device)}" ${(draft.devices||[]).includes(device)?'checked':''}>${device}</label>`).join('')}</div></fieldset>${field('otherDevices','Other devices (separate with commas)',(draft.devices||[]).filter(device=>!devices.includes(device)).join(', '))}<label class="choice"><input type="checkbox" id="noDevices" ${Array.isArray(draft.devices)&&!draft.devices.length?'checked':''}>No devices right now</label><p class="demo">This saves your device list only. No devices are connected and no health readings are imported. After integration, manage connections in More → Connected Health Data.</p>`;
 }else if(step===6){body=`<h2>Make the app comfortable</h2><p>Choose how you prefer to use Pulsewise. Change these anytime in <strong>More → Settings</strong>.</p><label for="textSize">Text size</label><select id="textSize">${options(['normal','large','extra large'],draft.accessibility.textSize)}</select><p class="text-preview">Your daily check-in, at your pace.</p><label class="choice"><input type="checkbox" id="reduceMotion" ${draft.accessibility.reduceMotion?'checked':''}>Reduce animation</label><fieldset><legend>Reminder preferences</legend><label class="choice"><input type="checkbox" id="checkinReminder" ${draft.reminders.checkin?'checked':''}>Daily check-in reminder</label><label class="choice"><input type="checkbox" id="medicationReminder" ${draft.reminders.medication?'checked':''}>Medication reminder</label></fieldset><p class="demo">Text size previews here. Reminder preferences are saved for future integration; this demo does not send notifications.</p>`;}
 content.innerHTML=body;
 document.body.dataset.textSize=draft.accessibility.textSize;
 document.body.classList.toggle('reduce-motion',draft.accessibility.reduceMotion);
 document.getElementById('actions').innerHTML=savedMode?'<a href="../index.html">Open existing app demo</a>':`${setupCompleted?'<button type="button" id="cancelProfile">Cancel</button>':''}${step>0?'<button type="button" id="back">Back</button>':''}${step<REVIEW_STEP?'<button type="button" id="skip">Skip for now</button>':''}<button class="primary" type="submit">${step===REVIEW_STEP?'Save profile':'Continue'}</button>`;
 content.querySelector('h2').tabIndex=-1; content.querySelector('h2').focus();
}
const get=id=>document.getElementById(id);
const comma=value=>value.split(',').map(s=>s.trim()).filter(Boolean);
function capture(){
 if(step===0){draft.displayName=get('displayName').value.trim();draft.ageRange=get('ageRange').value||null;draft.profileNotes=get('profileNotes').value.trim();}
 if(step===1){const values=[...form.querySelectorAll('[name=conditions]:checked')].map(x=>x.value).concat(comma(get('conditionOther').value));draft.conditions=values.length?values:get('noConditions').checked?[]:null;}
 if(step===2&&get('noMedications').checked)draft.medications=[];
 if(step===3){for(const [key,id,none] of [['dietaryPreferences','diet','noDiet'],['allergies','allergies','noAllergies']]){const values=comma(get(id).value);draft[key]=values.length?values:get(none).checked?[]:null;}}
 if(step===4){draft.trackingPreferences=[...form.querySelectorAll('[name=trackingPreferences]:checked')].map(x=>x.value);}
 if(step===5){const devices=[...form.querySelectorAll('[name=devices]:checked')].map(x=>x.value).concat(comma(get('otherDevices').value));draft.devices=devices.length?devices:get('noDevices').checked?[]:null;}
 if(step===6){draft.accessibility={textSize:get('textSize').value,reduceMotion:get('reduceMotion').checked};draft.reminders={checkin:get('checkinReminder').checked,medication:get('medicationReminder').checked};}
}
function medicationEditor(index=null){editingMedication=index;const m=index===null?{name:'',dose:'',schedule:''}:draft.medications[index];get('medEditor').hidden=false;get('medEditor').innerHTML=`<h3>${index===null?'Add':'Edit'} medication</h3>${field('medName','Medication name',m.name)}${field('medDose','Dose (optional)',m.dose)}${field('medSchedule','Schedule (optional)',m.schedule)}<div class="actions"><button type="button" id="cancelMed">Cancel</button><button type="button" id="saveMed">Save medication</button></div>`;get('medName').focus();}
form.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.id==='cancelProfile'){draft=await profileStore.loadProfile();savedMode=true;step=REVIEW_STEP;render();return;}
 if((b.id==='back'||b.id==='skip')&&step===2&&get('medEditor')&&!get('medEditor').hidden){get('message').textContent='Save or cancel the medication form before leaving this step.';return;}
 if(b.dataset.edit!==undefined){savedMode=false;step=Number(b.dataset.edit);render();}
 if(b.id==='back'){capture();step--;render();}
 if(b.id==='skip'){capture();step++;render();}
 if(b.id==='addMedication')medicationEditor();
 if(b.dataset.medEdit!==undefined)medicationEditor(Number(b.dataset.medEdit));
 if(b.dataset.medDelete!==undefined){draft.medications.splice(Number(b.dataset.medDelete),1);if(!draft.medications.length)draft.medications=null;render();}
 if(b.id==='cancelMed'){get('medEditor').hidden=true;}
 if(b.id==='saveMed'){const name=get('medName').value.trim();if(!name){get('message').textContent='Please enter the medication name.';get('medName').focus();return;}const m={id:editingMedication===null?crypto.randomUUID():draft.medications[editingMedication].id,name,dose:get('medDose').value.trim(),schedule:get('medSchedule').value.trim()};draft.medications??=[];if(editingMedication===null)draft.medications.push(m);else draft.medications[editingMedication]=m;render();}
});
form.addEventListener('change',async e=>{

 if(e.target.id==='noDevices'&&e.target.checked){form.querySelectorAll('[name=devices]').forEach(x=>x.checked=false);get('otherDevices').value='';}
 if(e.target.name==='devices'||e.target.id==='otherDevices')get('noDevices').checked=false;
 if(e.target.id==='textSize'){draft.accessibility.textSize=e.target.value;document.body.dataset.textSize=e.target.value;}
 if(e.target.id==='profilePhoto'){const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){get('message').textContent='Choose a PNG, JPEG or WebP image smaller than 2 MB.';return;}const reader=new FileReader();reader.onload=async()=>{draft.photo=reader.result;await profileStore.saveProfile(draft);render();};reader.readAsDataURL(file);return;}
if(e.target.id==='noMedications'&&e.target.checked&&(draft.medications||[]).length){e.target.checked=false;get('message').textContent='Remove listed medications first, or leave this option unchecked.';}if(e.target.id==='noConditions'&&e.target.checked){form.querySelectorAll('[name=conditions]').forEach(x=>x.checked=false);get('conditionOther').value='';}if(e.target.name==='conditions'||e.target.id==='conditionOther')get('noConditions').checked=false;for(const [id,none] of [['diet','noDiet'],['allergies','noAllergies']]){if(e.target.id===none&&e.target.checked)get(id).value='';if(e.target.id===id&&e.target.value.trim())get(none).checked=false;}});
form.addEventListener('submit',async e=>{e.preventDefault();if(step===2&&get('medEditor')&&!get('medEditor').hidden){get('message').textContent='Save or cancel the medication form before continuing.';return;}capture();if(step<REVIEW_STEP){step++;render();}else{try{draft.onboardingCompleted=true;draft=await profileStore.saveProfile(draft);savedMode=true;setupCompleted=true;render();}catch{get('message').textContent='Could not save. Your answers are still here. Please try again.';}}});
profileStore.loadProfile().then(profile=>{if(profile){draft=profile;savedMode=profile.onboardingCompleted;setupCompleted=savedMode;}render();});
