// Uses the existing backend development dependency; no browser or provider requests.
const {JSDOM}=require('../../backend/node_modules/jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{runScripts:'outside-only',url:'https://example.test/auth/'});
const w=dom.window,d=w.document;
w.fetch=()=>{throw new Error('Auth preview must not send network requests');};
w.eval(fs.readFileSync(path.join(root,'app.js'),'utf8'));
const click=s=>{assert(d.querySelector(s),s);d.querySelector(s).click();};
const set=(id,value)=>{d.getElementById(id).value=value;};
const text=id=>d.getElementById(id).textContent;
click('[type=submit]');assert(text('email-error'));assert.equal(d.activeElement.id,'email');
set('email','wrong');set('password','sample');click('[type=submit]');assert(text('email-error'));
set('email','demo@example.com');click('[data-toggle=password]');assert.equal(d.getElementById('password').type,'text');click('[data-toggle=password]');assert.equal(d.getElementById('password').type,'password');
click('[type=submit]');assert(text('status').includes('not connected'));assert.equal(d.getElementById('password').value,'');
click('[data-mode=signup]');set('email','demo@example.com');set('password','short');set('confirmPassword','different');click('[type=submit]');assert(text('password-error'));assert(text('confirmPassword-error'));
set('password','sample-password');set('confirmPassword','sample-password');click('[type=submit]');assert(text('status').includes('No account has been created'));assert.equal(d.getElementById('confirmPassword').value,'');
click('#google');assert(text('status').includes('not connected'));
click('[data-mode=signin]');click('[data-mode=reset]');assert.equal(d.getElementById('password'),null);set('email','demo@example.com');click('[type=submit]');assert(text('status').includes('No email has been sent'));
click('[data-mode=signin]');assert.equal(d.getElementById('email').value,'');assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);
dom.window.close();console.log('PASS: validation, password visibility, matching, screen switching, Google/reset unavailable states, password clearing and no storage.');
